# Generated by Django 4.0.4 on 2022-04-19 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('venue', '0001_initial'),
        ('artist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('date', models.DateField()),
                ('tour', models.CharField(max_length=256)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shows', to='artist.artist')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shows', to='venue.venue')),
            ],
        ),
        migrations.CreateModel(
            name='PerformedSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=256)),
                ('original_song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_performances', to='artist.song')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='show.show')),
            ],
        ),
    ]
