# Generated by Django 4.0.4 on 2022-04-19 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('disambiguation', models.CharField(blank=True, max_length=256, null=True)),
                ('mbid', models.CharField(max_length=256, unique=True)),
                ('name', models.CharField(max_length=256)),
                ('setlist_fm_url', models.CharField(blank=True, max_length=256, null=True)),
                ('sort_name', models.CharField(blank=True, max_length=256, null=True)),
                ('tmid', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('name', models.CharField(default='No release', max_length=256)),
                ('release_date', models.DateField()),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releases', to='artist.artist')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=256)),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='artist.release')),
            ],
        ),
    ]
