# Generated by Django 4.0.4 on 2022-04-19 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Artist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "disambiguation",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("mbid", models.CharField(max_length=256, unique=True)),
                ("name", models.CharField(max_length=256)),
                (
                    "setlist_fm_url",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("sort_name", models.CharField(blank=True, max_length=256, null=True)),
                ("tmid", models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Release",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="No release", max_length=256)),
                ("release_date", models.DateField()),
                (
                    "artist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="releases",
                        to="artist.artist",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                (
                    "release",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="songs",
                        to="artist.release",
                    ),
                ),
            ],
        ),
    ]
