# Generated by Django 4.0.4 on 2022-04-19 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('address', models.CharField(max_length=256)),
                ('capacity', models.CharField(max_length=256)),
                ('country', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=256)),
            ],
        ),
    ]
